# Changelog:
# 2025-05-07 HH:MM - Step 5 - Initial creation with default configurations.

# Default application configuration
# Settings here can be overridden by environment variables

app_name: "YieldFi AI Agent"
log_level: "INFO"

app:
  name: YieldFi AI Agent
  version: 0.1.0
  debug: false

data_source:
  type: mock  # Options: mock, twitter
  twitter:
    # Twitter API credentials should be set in .env file, not here

ai:
  provider: "xai" # or "google_palm"
  # API Keys are sourced from .env using AI__XAI_API_KEY and AI__GOOGLE_API_KEY respectively
  xai_api_key: null
  google_api_key: null
  xai_model: "grok-3-mini-beta"
  use_fallback: false
  xai_base_url: "https://api.x.ai/v1"
  google_palm_base_url: "https://generativelanguage.googleapis.com/v1beta" # Placeholder
  default_max_tokens: 1500
  default_temperature: 0.7

tweet_categories:
  - announcement
  - product-updates
  - community-updates
  - events

tone_analysis:
  enabled: true
  method: "textblob" # or "xai", "google_palm"

logging:
  level: INFO
  file: yieldfi_ai_agent.log

ui:
  theme: light  # Options: light, dark
  show_debug_info: false

data_paths:
  input: data/input
  output: data/output
  knowledge: data/docs

data_sources:
  type: "mock" # can be "twitter" later
  mock:
    tweets_file: "data/input/sample_tweets.json"
    accounts_file: "data/input/sample_accounts.json" 